#!/usr/bin/env ansible-playbook
#
# author: slm@slm.com
#
#
#
---

- name: Config root
  hosts: all                       # siehe ./hosts, datei mit managbaren systemen
  become: True
  tasks:

      # change vagrant login shell to zsh
    - name: change login shell
      user:
        name: root
        shell: /usr/bin/zsh

    - name: copy .bashrc
      copy: src=../files/.bashrc       dest=/root
      #copy: src=../files/.bashrc      dest=/home/{{ username }} owner={{ username }} group={{ username }}

    - name: copy .inputrc
      copy: src=../files/.inputrc      dest=/root

    - name: copy .vimrc
      copy: src=../files/.vimrc        dest=/root

    - name: copy .zshrc
      copy: src=../files/.zshrc        dest=/root

    - name: copy tmux.conf
      copy: src=../files/.tmux.conf   dest=/root

    # neovim profile
    - name: copy init.vim
      copy: src=../files/init.vim     dest=/root/.config/nvim/

    - name: copy maps.vim
      copy: src=../files/maps.vim     dest=/root/.config/nvim/

    - name: copy settings.vim
      copy: src=../files/settings.vim dest=/root/.config/nvim/

    - name: copy plugins.vim
      copy: src=../files/plugins.vim  dest=/root/.config/nvim/

    - name: copy tmux.conf
      copy: src=../files/.tmux.conf   dest=/root/.config/nvim/

    # custom zsh plugins
    - name: copy slm-aliases.plugin.zsh
      copy: src=../files/slm-aliases.plugin.zsh           dest=/root/.local/plugins/

    - name: copy slm-colored-man-pages.plugin.zsh
      copy: src=../files/slm-colored-man-pages.plugin.zsh dest=/root/.local/plugins/

    - name: copy slm-fzf.plugin.zsh
      copy: src=../files/slm-fzf.plugin.zsh               dest=/root/.local/plugins/

    - name: copy slm-powerline.plugin.zsh
      copy: src=../files/slm-powerline.plugin.zsh         dest=/root/.local/plugins/


