#!/usr/bin/env ansible-playbook
---
- name: Configure lvim-tech
  hosts: all
  become: True
  become_user: root
  tasks:

        - name: Check if nvim.appimage exists
          stat:
            path: ~/nvim.appimage
          register: stat_oh_my_zsh_result

        - name: Cloning nvim.appimage
          git:
            repo=https://github.com/nvim.appimage????
            dest=~/appimage

        - name: Check if powerlever10k exists
          stat:
            path: ~/.oh-my-zsh/custom/themes/powerlevel10k
          register: stat_powerlevel10k_result

        - name: Cloning  powerlever10k
          git:
            repo=https://github.com/romkatv/powerlevel10k.git
            dest=.oh-my-zsh/custom/themes/powerlevel10k
          when: not stat_powerlevel10k_result.stat.exists

        - name: Check if .zshrc exists
          stat:
            path: ~/.zshrc
          register: stat_rc_result

        - name: Creating new ~/.zshrc
          copy:
            src=~/.oh-my-zsh/templates/zshrc.zsh-template
            dest=~/.zshrc
          when: not stat_rc_result.stat.exists

        # eigene plugins
        - name: copy slm-aliases.plugin.zsh
          copy: src=files/slm-aliases.plugin.zsh dest=/home/christoph/.oh-my-zsh/custom/plugins/slm-aliases/

        - name: copy slm-colored-man-pages.plugin.zsh
          copy: src=files/slm-colored-man-pages.plugin.zsh dest=/home/christoph/.oh-my-zsh/custom/plugins/slm-colored-man-pages/

