# ~/.tmuxinator/beets.yml

name: beets
root: ~/ws/beets

on_project_start:
 sudo mount --label music-lib-0.1 /mnt/music-lib-0.1;
 sudo mount --label music-source /mnt/music-source;

#pre_window: export BEETSDIR=conf-test-inside-directory
#pre_window: export BEETSDIR=/home/christoph/ws/beets/conf-test-music-lib
#pre_window: export BEETSDIR=/home/christoph/ws/beets/conf-test-inside-directory
pre_window:
 export BEETSDIR=/home/christoph/ws/beets/conf-music-lib-0.1
 export PATH=/home/christoph/bin:/home/christoph/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

 # Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: edit-beets-yml

windows:
 - edit-dir: $EDITOR .
 - test-window: clear
 - log-window: clear; tail -f $BEETSDIR/beetlog.txt
 - edit-beets-yml:
     layout: 8fe1,178x55,0,0{116x55,0,0,69,61x55,117,0[61x27,117,0,72,61x27,117,28,73]}
     panes:
      - $EDITOR ~/.tmuxinator/beets.yml
      - clear; figlet ". . . mux . . ."
      - clear; figlet ' . . . beets . .'
