# ~/.tmuxinator/brakina.yml

name: brakina
root: ~/ws/brakina

startup_pane: 1
pre_window: reset

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf
# tmux_options: -v

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: brakina:ssh-brakina

windows:
 - ssh-brakina:
    # layout muss noch geändert werden
    layout: 8fe1,178x55,0,0{116x55,0,0,69,61x55,117,0[61x27,117,0,72,61x27,117,28,73]}
    panes:
     - ssh u0_a109@brakina -p8022
     - ssh u0_a109@brakina -p8022
     - ssh u0_a109@brakina -p8022
 - control-brakina:
    # layout muss noch geändert werden
    layout: 8fe1,178x55,0,0{116x55,0,0,69,61x55,117,0[61x27,117,0,72,61x27,117,28,73]}
    panes:
     - ssh -t u0_a109@brakina -p8022
     - ssh -t u0_a109@brakina -p8022 htop
     - ssh -t u0_a109@brakina -p8022
 - edit-yml:
    # layout aus layout-template-dir
    layout: 8fe1,178x55,0,0{116x55,0,0,69,61x55,117,0[61x27,117,0,72,61x27,117,28,73]}
    panes:
     - $EDITOR ~/.tmuxinator/brakina.yml
     - ssh -t u0_a109@brakina -p8022 neofetch
     -
