#!/usr/bin/env ansible-playbook
#
# author: slm@slm.com
#
---

- name: Install packages
  hosts: enterprise-container         # siehe ./hosts, datei mit managbaren systemen
  become: true
  tasks:

    # multiple packages
    - name: install packages
      become: true
      become_user: root
      apt:
        pkg:
          - atop
          - autotools-dev
          - bat
          - cmatrix
          - cowsay
          - debconf-utils
          - fd-find
          - git
          - locate
          - lolcat
          - neofetch
          - neovim
          - net-tools
          - nmap
          - powerline
          - powerline-doc
          - speedtest-cli
          - tree
          - zsh
        update_cache: true
