#!/usr/bin/env ansible-playbook
#
# author: slm@slm.com
#
---

- name: Install multi-media
  hosts: all         # siehe ./hosts, datei mit managbaren systemen
  become: true
  tasks:

    # multiple packages
    - name: install packages
      become: true
      become_user: root
      apt:
        pkg:
          - mpg123
        update_cache: true

    # system default local
    - name: copy music
      copy: src=../files/test-data/music/   dest=/mnt/music owner=root group=root
